### ISSUE TITLE
No ZTF photometry on source page

### ISSUE THREAD

**Issue by yaoyuhan** [fritz-marshal/fritz-beta-feedback#23]
Hi, I saved the source to fritz https://fritz.science/source/ZTF20achvlbs
but there is no plotted photometry. May I know why? Thanks! --Yuhan

**Comment by dmitryduev** [comment]
@yaoyuhan where did you save it from? The Alerts page?

**Comment by yaoyuhan** [comment]
I saved it using http://skyportal.io/docs/api#/paths/~1api~1sources/post. Originally I did not specify the gorup id, so it was saved to all my groups. I then manually unsaved it from all other groups except `fast`.

**Comment by dmitryduev** [comment]
I see. Now you need to manually post the photometry and the thumbnails. 
The Fritz-specific SP api endpoint to use if you want all that to happen in one go automatically would be
`/api/alerts/ztf/<objectId>.POST`. If you don't provide any data with it, Fritz will use the latest candid to pull the thumbnails and save it to all the groups you are a member of (respecting ACLs). You can set `data={"candid": <candid>, "group_ids": [<id_1>, <id_2>, ...]}`.

We are now refactoring Fritz so that all the API docs show up on `fritz.science`, sorry about that and please stay tuned.
