### ISSUE TITLE
Object not properly displayed on the Groups page

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#25]
Hi

When you display an object on Groups -> Sources -> Groups Sources, the light curves and spectra are not shown.

<img width="1920" alt="Screenshot 2020-11-11 at 19 49 17" src="https://user-images.githubusercontent.com/11585543/98852776-78f55c80-2458-11eb-8596-3ecaaabc043a.png">

**Comment by dannygoldstein** [comment]
@guynir42

**Comment by kmshin1397** [comment]
Hi @steveschulze,

Do you see this on the corresponding source pages for these sources as well? So if you click on the source id for a source where the plots do not show, do you see the plots on the source page for that source? My first guess would that these sources simply do not have photometry/spectra data yet. Which means we should probably relay that in text instead of displaying an empty plot.

**Comment by guynir42** [comment]
Will be closed by skyportal #1561

**Comment by guynir42** [comment]
closed by skyportal #1561
