### ISSUE TITLE
No image/ref/sub but only sdss/dr8

### ISSUE THREAD

**Issue by rjoebruch** [fritz-marshal/fritz-beta-feedback#62]
On the scanning page of RCF, there are candidates not showing any image from P48 

1. Go to scanning page, choose time 2020-11-26 00:00 til 2020-11-26 23:59
2. Choose RCF (leave the unsaved events option)
3. Scroll down to 16th candidate row

 - Fritz version:  v0.9.dev0+git20201125.95d9e76+fritz.7d7a638.
 - Browser
   - [ Chrome ] I'm browsing on a desktop
  

![Screen Shot 2020-11-26 at 15 57 31](https://user-images.githubusercontent.com/45436034/100359481-49ba2000-3000-11eb-886d-c32962d618dd.png)

**Comment by dannygoldstein** [comment]
I believe this happens when AMPEL posts objects to Fritz, can you confirm @jvansanten?

**Comment by jvansanten** [comment]
That's correct, and has to do with the way that candidate ownership semantics interact with thumbnails. Thumbnails are tied to a source, not a candidate, and our bot user has no way to know if a source exists in a secret program it doesn’t have access to. This means that we can't post cutouts without blowing away ones that might already exist. Kowalski can in principle know what exists, since its user can see all programs, but only posts thumbnails for sources it considers new. We're holding off posting thumbnails for candidates selected by Ampel channels until https://github.com/skyportal/skyportal/issues/1361 is resolved, as this seemed less harmful than overwriting thumbnails with our own.

**Comment by rjoebruch** [comment]
thanks for your response! staying tuned for developments

**Comment by dmitryduev** [comment]
There's a Kowalski tool that we run periodically (https://github.com/dmitryduev/kowalski/blob/master/tools/update_ztf_thumbnails_fritz.py) that should take care of this. Closing.
