### ISSUE TITLE
Limiting magnitude measurement difference between Fritz and Marshal

### ISSUE THREAD

**Issue by rjoebruch** [fritz-marshal/fritz-beta-feedback#65]
**Describe the bug**
The photometry displayed on the marshal and Fritz have different value (especially for the limiting magnitude measurement)

**To Reproduce**
1. Go to http://skipper.caltech.edu:8080/cgi-bin/growth/plot_lc.cgi?name=ZTF20acufmte 
2. (and) Go to https://fritz.science/source/ZTF20acufmte 
3. download the photometry table of ZTF20acufmte from Fritz 
4. Compare limiting magnitudes

**Expected behavior**
We'd expect to have consistent limiting magnitude measurements

**Screenshots**
Screen Shot 2020-11-29 at 14.29.08 : Fritz LC
Screen Shot 2020-11-29 at 14 29 13 : Marshal LC

**Platform information:**
 - Fritz version:  v0.9.dev0+git20201125.95d9e76+fritz.7d7a638

![Screen Shot 2020-11-29 at 14 29 08](https://user-images.githubusercontent.com/45436034/100541946-f63e1100-324f-11eb-8ade-6949c9e8675e.png)
![Screen Shot 2020-11-29 at 14 29 13](https://user-images.githubusercontent.com/45436034/100541949-f9390180-324f-11eb-8254-e2735f853614.png)

 - Browser
   - [Chrome] I'm browsing on a desktop

**Comment by dannygoldstein** [comment]
@rjoebruch the limiting magnitudes on Fritz are based on the 5-sigma flux error at the location of the transient whereas the limiting magnitudes on the marshal are an average quantity across the entire image. in order to bring the values on fritz into agreement with what is on the GM, we need to merge https://app.zenhub.com/workspace/o/fritz-marshal/fritz/issues/87. but what is currently there is in some sense a more accurate view of the magnitude limit
